#!/usr/bin/env php
<?php

##################################################
# Config
##################################################

if (!defined('ERRORS')) {
    define('ERRORS', true);
}
if (!defined('PACKAGED')) {
    define('PACKAGED', false);
}

# Path to pcon console_abstract.php
if (!defined('CONSOLE_ABSTRACT_PATH')) {
    define(
        'CONSOLE_ABSTRACT_PATH',
        __DIR__ . DIRECTORY_SEPARATOR .
        'pcon' . DIRECTORY_SEPARATOR .
        'src' . DIRECTORY_SEPARATOR .
        'console_abstract.php'
    );
}

if (!is_file(CONSOLE_ABSTRACT_PATH)) {
    echo "ERROR: Console Abstract not found - '" . CONSOLE_ABSTRACT_PATH . "'\n";
    echo " - Symlink your pcon folder to '" . __DIR__ . DIRECTORY_SEPARATOR . "pcon' to resolve this issue\n";
    echo "----------------------------------------\n";
    throw new Exception("Missing console abstract");
}

# Paths to other includes
$src_includes = array(
    __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'config_keys.php',
    __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'pssh_config.php',
    __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'pssh.php',
);

##################################################

if (empty($_PACKAGING)) { // defined when loading file to do packaging
    require_once CONSOLE_ABSTRACT_PATH;
}

# vim: syntax=php
