#!/usr/bin/env php
<?php
/**
 * Acts as the entry pointkduring development; initializes the tool
 *
 * - Sets a few constants and loads in primary logic files
 * - **NOTE:** actual file is "pcon" with no extension - name temporarily modified for linting & doc generation
 *
 * @package pcon
 * @author  chrisputnam9
 */

// Miscellaneous configuration
if (! defined('ERRORS')) {
    /*
     * @var boolean Whether to show errors or not.
     * @global
     * @used-by Console_Abstract
     */
    define('ERRORS', true);
}
if (! defined('PACKAGED')) {
    /*
     * @var boolean Whether the tool is packaged (vs. unpackaged / development mode)
     * @global
     * @used-by Console_Abstract
     */
    define('PACKAGED', false);
}

// Path to pcon console_abstract.php
if (! defined('CONSOLE_ABSTRACT_PATH')) {
    // For PCon specifically, check src
    $console_path =
        __DIR__ . DIRECTORY_SEPARATOR .
        'src' . DIRECTORY_SEPARATOR .
        'console_abstract.php';

    // For other tools, check pcon
    if (!is_file($console_path)) {
        $console_path =
            __DIR__ . DIRECTORY_SEPARATOR .
            'pcon' . DIRECTORY_SEPARATOR .
            'src' . DIRECTORY_SEPARATOR .
            'console_abstract.php';
    }

    if (!is_file($console_path)) {
        echo "ERROR: Console Abstract not found - '" . $console_path . "'\n";
        echo " - Symlink your pcon folder to '" . __DIR__ . DIRECTORY_SEPARATOR . "pcon' to resolve this issue\n";
        echo "----------------------------------------\n";
        throw new Exception("Missing console abstract");
    }

    /*
     * @var string The path the the Console_Abstract class file to be loaded below.
     * @ignore
     */
    define('CONSOLE_ABSTRACT_PATH', $console_path);
}//end if

/*
 * @var array Source files to be loaded for this tool.
 * @global
 * @used-by Console_Abstract
 */
$src_includes = array(
    __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'config_keys.php',
    __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'pssh_config.php',
    __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'pssh.php',
);


if (empty($_PACKAGING)) {
    // Defined when loading file to do packaging
    require_once CONSOLE_ABSTRACT_PATH;
}

// vim: syntax=php
